class ListaIconos:
    
    ICONOS = {
        "datos": "resources/iconos/adicional/datos.svg",
        "visor": "resources/iconos/adicional/3d_icon.svg",
        "desplazamiento": "resources/iconos/adicional/desplazamiento.svg",
        "velocidad": "resources/iconos/adicional/velocidad.svg",
        "inclinometros": "resources/iconos/adicional/inclinometros.svg",
        "piezometros": "resources/iconos/adicional/piezometros.svg",
        "celdas": "resources/iconos/adicional/celdas.svg",
        "acelerografos": "resources/iconos/adicional/acelerografos.svg",
        "tdr": "resources/iconos/adicional/tdr.svg",
        "analisis": "resources/iconos/adicional/analisis.svg",
        "reporte": "resources/iconos/adicional/reporte.svg",
        "usuarios": "resources/iconos/adicional/usuarios.svg",
        "menu_bar": "resources/iconos/fontawesome/solid/caret-right.svg",        
        "exportar_tabla": "resources/iconos/fontawesome/solid/file-arrow-down.svg",
        "refrescar_general": "resources/iconos/fontawesome/solid/rotate.svg",
        "vista_3d": "resources/iconos/fontawesome/solid/cube.svg",
        "vista_corte": "resources/iconos/fontawesome/solid/puzzle-piece.svg",
        "vista_dtm": "resources/iconos/fontawesome/brands/hive.svg",
        "vectores": "resources/iconos/fontawesome/solid/arrow-down-long.svg",
        "escalar_inclinometro": "resources/iconos/fontawesome/brands/linode.svg",
        "cubo_corte": "resources/iconos/fontawesome/solid/vector-square.svg",
        "corte_3d": "resources/iconos/fontawesome/solid/scissors.svg",
        "ajustes_visor": "resources/iconos/fontawesome/solid/wrench.svg",
        "resumen_desplazamiento": "resources/iconos/fontawesome/solid/table-list.svg",
        "add_imagen_reporte": "resources/iconos/fontawesome/regular/images.svg",
        "refrescar_grafico": "resources/iconos/fontawesome/solid/retweet.svg",
        "configurar_ejes": "resources/iconos/fontawesome/solid/arrow-down-up-across-line.svg",
        "tendencia": "resources/iconos/fontawesome/solid/arrow-trend-up.svg",
        "limpieza": "resources/iconos/fontawesome/solid/broom.svg",
        "primera_pagina": "resources/iconos/fontawesome/solid/angles-left.svg",
        "ultima_pagina": "resources/iconos/fontawesome/solid/angles-right.svg",
        "siguiente_pagina":"resources/iconos/fontawesome/solid/angle-right.svg", 
        "anterior_pagina":"resources/iconos/fontawesome/solid/angle-left.svg",
        "exportar_dxf": "resources/iconos/fontawesome/solid/file-export.svg",
        "imagen_reporte": "resources/iconos/fontawesome/solid/file-image.svg",
        "asistente_voz": "resources/iconos/fontawesome/solid/headset.svg",
        "animacion_trayectoria": "resources/iconos/fontawesome/solid/circle-nodes.svg",
        "planos_estereografia": "resources/iconos/fontawesome/solid/globe.svg",
        "ocultar": "resources/iconos/fontawesome/solid/eye-slash.svg",
        "mostrar": "resources/iconos/fontawesome/solid/eye.svg",
        "exportar_reporte": "resources/iconos/fontawesome/solid/file-lines.svg",
        "zoom_in": "resources/iconos/fontawesome/solid/magnifying-glass-plus.svg",
        "zoom_out": "resources/iconos/fontawesome/solid/magnifying-glass-minus.svg",
        "guardar_reporte": "resources/iconos/fontawesome/solid/sd-card.svg",
        "firma_reporte": "resources/iconos/fontawesome/solid/signature.svg",
        "subir_archivo": "resources/iconos/fontawesome/solid/arrow-up-from-bracket.svg",
        "calendario": "resources/iconos/fontawesome/solid/calendar-days.svg",
        "profundidad": "resources/iconos/fontawesome/solid/layer-group.svg",
        "regresar": "resources/iconos/fontawesome/solid/left-long.svg",
        "dibujar": "resources/iconos/fontawesome/solid/pencil.svg",
        "comparar": "resources/iconos/fontawesome/solid/photogrammetry-svgrepo-com.svg",
        "lidar": "resources/iconos/fontawesome/solid/map_heat_icon_216145.svg",
        "umbral": "resources/iconos/fontawesome/solid/brush.svg",
        "estrato": "resources/iconos/fontawesome/solid/water.svg",
        "desplaza": "resources/iconos/fontawesome/solid/chart-area.svg",
        "basura": "resources/iconos/fontawesome/solid/trash.svg",
        "imagenes": "resources/iconos/fontawesome/regular/file-image.svg",
        "subirimagen": "resources/iconos/fontawesome/solid/file-image.svg",
        "oculta_mostrar": "resources/iconos/fontawesome/solid/left-right.svg",
        "calculadora": "resources/iconos/fontawesome/solid/calculator.svg",
        "adduser": "resources/iconos/fontawesome/solid/user-plus.svg",
        "desviacion": "resources/iconos/adicional/deviation.svg",
        "descargar": "resources/iconos/fontawesome/solid/download.svg",
        "backup":"resources/iconos/adicional/backup.svg",
        "Dashboard":"resources/iconos/adicional/dashboard.svg",
        "csv":"resources/iconos/fontawesome/solid/file-csv.svg",
        "umbral2":"resources/iconos/fontawesome/solid/paint-roller.svg",
        "limpieza_ruido":"resources/iconos/fontawesome/solid/searchengin.svg",
        "limpieza_ruido_manual":"resources/iconos/fontawesome/solid/diagram-project.svg",
        "clipboard":"resources/iconos/fontawesome/solid/clipboard.svg",
        "nuevo": "resources/iconos/fontawesome/solid/plus.svg",
        "reloj": "resources/iconos/fontawesome/solid/clock.svg",
    }
